import Main from "../modules/main/Main";
import Head from "next/head";
import { useState } from "react";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { useDispatch } from "react-redux";
import Query from "../services/query"

import { setTokenUser } from "../redux/siteDataReducer";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();

  const categoryId = true;
  const [data, setData] = useState([]);
  const [token1, setToken1] = useState(null);
  useEffect(() => {
    // Check if window object is defined (client-side)
    if (typeof window !== "undefined") {
      const storedToken = localStorage.getItem("access_token");
      setToken1(storedToken);
      dispatch(setTokenUser(storedToken));
    }
  }, [router]);
  // console.log(token1);
  return (
    <>
      <Head>
        <title>XNARX - MARKET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/Assets/Images/news/new3.png"} />
      </Head>
      <Query>
        <Main />
      </Query>

    </>
  );
}
